
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <?php
    include('Search/config.php');
    ?>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Header</title>
    <link rel="stylesheet" href="../css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link href="../css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="../css/bootstrap.theme.css" rel="stylesheet">
    <link href="../css/style.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed|Rubik" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
</head>

<body>



<?php

require_once ('Template2/header2.phtml');
?>


<div class="container">
    <div class="row">
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">

                    <form  action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
                        <div class="modal-body">
                            <p>What is 10 + 10</p>
                            <label for=''>Type your answer here</label>
                            <input name='answer' style='width: 100px; margin: 0 auto;' type='number' min='0' class='form-control'>
                            <input class='card-title text-center' name='int1' style='display: none' value= 6>
                            <input class='card-title text-center' name='int2' style='display: none' value= 39>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" name="answerButton" class="btn btn-default" >Enter</button>
                        </div>
                </div>
                </form>
            </div>
        </div>
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Sign In</h5>
                    <form class="form-signin" method="post" action="auction2.php" >
                        <div class="form-label-group">
                            <label for="inputEmail">Email address:</label>
                            <input type="email" id="inputEmail" class="form-control" placeholder="Email address" name="email" value=''  required autofocus>
                        </div>
                        <div class="form-label-group">
                            <label for="inputPassword">Password:</label>
                            <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password" required>
                        </div>
                        <div class="custom-control custom-checkbox mb-3">
                            <input type="checkbox" class="custom-control-input" id="customCheck1">
                            <label class="custom-control-label" for="customCheck1">Remember password</label>
                        </div>
                        <button class="btn btn-dark btn-primary btn-block text-uppercase" type="submit" name="submit">Sign in</button>
                        <hr class="my-4">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php

$view = new stdClass();
$view->pageTitle = 'Auction';

require_once ('Template2/footer2.html');
?>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</html>




<style>


    @charset "utf-8";
    /* CSS Document */
    body{
        font-family: 'Rubik', sans-serif;
        background:#BBBBBB;
    }
    /***********************************/
    #lowrbdy{
        width:100%;
        height:581px;
        position:absolute;
        top:74px;
        left:0px;
    }
    #lowrbdy img{
        width:100%;
        height:100%;
    }
    /***********************************/
    header{
        width:100%;
        height:auto;
        background:#adb5bd;
        box-shadow:0px 0px 8px 2px #333;
        position:fixed;
        z-index:99999;
        top:0px;
        left:0px;
    }
    /***********************************/
    .logo{
        width:181px;
        height:61px;
        position:relative;
        top:5px;
        left:10px;
        float:left;
    }
    .logo a{
        text-decoration:none;
        color:#fff;
        font-size:60px;
        margin:0px 20px;
        line-height:0.9em;
    }
    /***********************************/
    .srbox{
        width:580px;
        height:70px;
        float:left;
        margin-left:120px;
        margin-top:4px;
    }
    .textbox{
        border-radius: 8px 0px 0px 8px;
        background-color:#fff;
        float:left;
        border:none;
        height:40px;
        padding:1px 12px;
        font-size:15px;
        line-height: 1.42857;
        color:#000;
        width:420px;
        margin-top:13px;
    }
    .query-submit{
        border-radius: 0px 8px 8px 0px;
        cursor:pointer;
        background:#fbfbfb;
        width:85px;
        padding:1px 6px;
        float:left;
        border:none;
        margin-top:13px;
        height:42px;
    }
    .textbox-clr{
        cursor:pointer;
        background:#fff;
        width:20px;
        height:42px;
        float:left;
        border:none;
        margin-top:13px;
        text-align:center;
    }
    /***********************************/
    .acount{
        width:170px;
        height:30px;
        float:left;
        margin-top:27px;
        margin-left:40px;
    }
    .aclogo{
        width:20px;
        height:20px;
        float:left;
        border:2px solid #fff;
        border-radius:50%;
        text-align:center;
    }
    .actext{
        width:130px;
        float:left;
        line-height:1.6em;
        margin-left:8px;
        font-size:15px;
        color:#fff;
    }
    /***********************************/
    .cart{
        width:120px;
        height:36px;
        float:left;
        border:2px solid #fff;
        border-radius:40px;
        margin-top:18px;
        margin-left:40px;
    }
    .cart i{
        line-height:1.6em;
        color:#fff;
        font-size:20px;
        margin-left:10px;
        float:left;
    }
    .cart-e{
        color:#fff;
        font-size:20px;
        line-height:1.6em;
        float:left;
        margin:0px;
        margin-left:10px;
    }
    .cart-f{
        color:#000;
        float:left;
        background:#fff;
        padding:2px 6px;
        border-radius:50%;
        margin:5px 0px 0px 11px;
        font-size:16px;
        line-height: normal;
    }
    /***********************************/
    #search-layer{
        position:absolute;
        background:rgba(255,255,255,0.5);
        z-index:9;
        left:0px;
        top:0px;
    }
    /***********************************/
    #livesearch{
        z-index:9999;
        background:#0071b4;
        max-height:260px;
        overflow:auto;
        width:92%;
        box-shadow:0px 2px 4px #444;
        margin-left:1.2%;
    }
    /***********************************/
    .live-outer{
        width:100%;
        height:60px;
        border-bottom:1px solid #ccc;
        background:#fff;
    }
    .live-outer:hover{
        background:#F3F3F3;
    }
    .live-im{
        float:left;
        width:10%;
        height:60px;
    }
    .live-im img{
        width:100%;
        height:100%;
    }
    .live-product-det{
        float:left;
        width:90%;
        height:60px;
    }
    .live-product-name{
        width:100%;
        height:22px;
        margin-top:4px;
    }
    .live-product-name p{
        margin:0px;
        color:#333;
        text-shadow: 1px 1px 1px #DDDDDD;
        font-size:17px;
    }
    .live-product-price{
        width:100%;
        height:25px;
    }
    .live-product-price-text{
        float:left;
        width:50%;
    }
    .live-product-price-text p{
        margin:0px;
        font-size:16px;
    }
    .link-p-colr{
        color:#333;
    }
</style>