<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="../../css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="../../css/bootstrap.theme.css" rel="stylesheet">
    <link href="../../css/style.css" rel="stylesheet">

    <title>Home</title>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <a href="Index.php" class="navbar-brand">Auction</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarMenu">
            <ul class="navbar-nav dropdown-menu-lg-left">
                <li class="nav-item"></li>
                <li class="nav-item">
                    <a href="auction.php" class="nav-link">Catalogue</a>
                </li>
                <li class="nav-item">
                    <a href="list.php" class="nav-link">Bid List</a>
                </li>
                <li class="nav-item">
                    <a href="login.php" class="nav-link">Login</a>
                </li>        </ul>
            <form class="form-inline my-2 my-lg-0" action="  " method="post">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" name="searchText">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit" name="Search">Search</button>
            </form>
        </div>
    </nav>

</head>

