<!doctype html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>Live Search</title>
    <?php
    include('config.php');
    ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed|Rubik" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <!-- Bootstrap core CSS -->
    <link href="../../css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="../../css/bootstrap.theme.css" rel="stylesheet">
    <link href="../../css/style.css" rel="stylesheet">

</head>

<body>
<header>
    <?php
    include('head.phtml');
    ?>
</header>





<?php
session_start();
$database_name = "aee318_auction";
$con = mysqli_connect("poseidon.salford.ac.uk","aee318","1bd6nS33Gt2nDNS",$database_name);

if (isset($_POST["auction"])){
    if (isset($_SESSION["BidList"])){
        $auction_array_auctionID = array_column($_SESSION["auction"],"auctionID");
        if (!in_array($_GET["id"],$auction_array_auctionID)){
            $count = count($_SESSION["cart"]);
            $auction_array = array(
                'auctionID' => $_GET["auctionID"],
                'itemTitle' => $_POST["ItemTitle"],
                'description' => $_POST["description"],
                'productImage' => $_POST["productImage"],
            );
            $_SESSION["cart"][$count] = $auction_array;
            echo '<script>window.location="bidList.php"</script>';
        }else{
            echo '<script>alert("Product is already Added to Cart")</script>';
            echo '<script>window.location="bidList.php"</script>';
        }
    }else{
        $auction_array = array(
            'auctionID' => $_GET["auctionIDd"],
            'itemTitle' => $_POST["itemTitle"],
            'description' => $_POST["description"],
            'productImage' => $_POST["productImage"],
        );
        $_SESSION["BidList"][0] = $auction_array;
    }
}

if (isset($_GET["action"])){
    if ($_GET["action"] == "delete"){
        foreach ($_SESSION["BidList"] as $keys => $value){
            if ($value["auctionID"] == $_GET["auctionID"]){
                unset($_SESSION["cart"][$keys]);
                echo '<script>alert("Product has been Removed...!")</script>';
                echo '<script>window.location="bidList.php"</script>';
            }
        }
    }
}

?>

<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bid List</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <style>
        @import url('https://fonts.googleapis.com/css?family=Titillium+Web');

        *{
            font-family: 'Titillium Web', sans-serif;
        }
        .product{
            border: 1px solid #eaeaec;
            margin: -1px 19px 3px -1px;
            padding: 10px;
            text-align: center;
            background-color: #efefef;
        }
        table, th, tr{
            text-align: center;
        }
        .title2{
            text-align: center;
            color: #66afe9;
            background-color: #efefef;
            padding: 2%;
        }
        h2{
            text-align: center;
            color: #66afe9;
            background-color: #efefef;
            padding: 2%;
        }
        table th{
            background-color: #efefef;
        }
    </style>
</head>
<body>

<div class="container" style="width: 65%">
    <h2>Bid List</h2>
    <?php
    $query = "SELECT * FROM auction ORDER BY auctionID ASC Limit 1 ";
    $result = mysqli_query($con,$query);
    if(mysqli_num_rows($result) > 0) {

        while ($row = mysqli_fetch_array($result)) {

            ?>
            <div class="col-md-3">

                <form method="post" action="emptyList.php?action=add&id=<?php echo $row["auctionID"]; ?>">

                    <div class="product">
                        <img src="<?php echo $row["productImage"]; ?>" class="img-responsive">
                        <h5 class="text-info"><?php echo $row["itemTitle"]; ?></h5>
                        <h5 class="text-danger"><?php echo $row["itemID"]; ?></h5>
                        <input type="text" name="quantity" class="form-control" value="1">
                        <input type="hidden" name="hidden_name" value="<?php echo $row["postingUser"]; ?>">
                        <input type="hidden" name="hidden_price" value="<?php echo $row["description"]; ?>">
                        <input type="submit" name="add" style="margin-top: 5px;" class="btn btn-success"
                               value="Remove">
                    </div>
                </form>
            </div>
            <?php
        }
    }
    ?>

    <div style="clear: both"></div>
    <div class="table-responsive">
        <table class="table table-bordered">


            <?php
            if(!empty($_SESSION["auction"])){
                $total = 0;
                foreach ($_SESSION["auction"] as $key => $value) {
                    ?>
                    <tr>
                        <td><?php echo $value["itemTitle"]; ?></td>
                        <td><?php echo $value["itemID"]; ?></td>
                        <td>$ <?php echo $value["PostingUser"]; ?></td>

                        <td>
                            $ <?php echo number_format($value["item_quantity"] * $value["product_price"], 2); ?></td>
                        <td><a href="bidList.php?action=delete&id=<?php echo $value["itemID"]; ?>"><span
                                    class="text-danger">Remove Item</span></a></td>


                    </tr>
                    <?php
                    $total = $total + ($value["item_quantity"] * $value["product_price"]);
                }
                ?>
                <tr>
                    <td colspan="3" align="right">Total</td>
                    <th align="right">$ <?php echo number_format($total, 2); ?></th>
                    <td></td>
                </tr>
                <?php
            }
            ?>
        </table>
    </div>

</div>


</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
</html>

<style>
@charset "utf-8";
/* CSS Document */
body{
font-family: 'Rubik', sans-serif;
background:#BBBBBB;
}
/***********************************/
#lowrbdy{
width:100%;
height:581px;
position:absolute;
top:74px;
left:0px;
}
#lowrbdy img{
width:100%;
height:100%;
}
/***********************************/
header{
width:100%;
height:auto;
background:#adb5bd;
box-shadow:0px 0px 8px 2px #333;
position:fixed;
z-index:99999;
top:0px;
left:0px;
}
/***********************************/
.logo{
width:181px;
height:61px;
position:relative;
top:5px;
left:10px;
float:left;
}
.logo a{
text-decoration:none;
color:#fff;
font-size:60px;
margin:0px 20px;
line-height:0.9em;
}
/***********************************/
.srbox{
width:580px;
height:70px;
float:left;
margin-left:120px;
margin-top:4px;
}
.textbox{
border-radius: 8px 0px 0px 8px;
background-color:#fff;
float:left;
border:none;
height:40px;
padding:1px 12px;
font-size:15px;
line-height: 1.42857;
color:#000;
width:420px;
margin-top:13px;
}
.query-submit{
border-radius: 0px 8px 8px 0px;
cursor:pointer;
background:#fbfbfb;
width:85px;
padding:1px 6px;
float:left;
border:none;
margin-top:13px;
height:42px;
}
.textbox-clr{
cursor:pointer;
background:#fff;
width:20px;
height:42px;
float:left;
border:none;
margin-top:13px;
text-align:center;
}
/***********************************/
.acount{
width:170px;
height:30px;
float:left;
margin-top:27px;
margin-left:40px;
}
.aclogo{
width:20px;
height:20px;
float:left;
border:2px solid #fff;
border-radius:50%;
text-align:center;
}
.actext{
width:130px;
float:left;
line-height:1.6em;
margin-left:8px;
font-size:15px;
color:#fff;
}
/***********************************/
.cart{
width:120px;
height:36px;
float:left;
border:2px solid #fff;
border-radius:40px;
margin-top:18px;
margin-left:40px;
}
.cart i{
line-height:1.6em;
color:#fff;
font-size:20px;
margin-left:10px;
float:left;
}
.cart-e{
color:#fff;
font-size:20px;
line-height:1.6em;
float:left;
margin:0px;
margin-left:10px;
}
.cart-f{
color:#000;
float:left;
background:#fff;
padding:2px 6px;
border-radius:50%;
margin:5px 0px 0px 11px;
font-size:16px;
line-height: normal;
}
/***********************************/
#search-layer{
position:absolute;
background:rgba(255,255,255,0.5);
z-index:9;
left:0px;
top:0px;
}
/***********************************/
#livesearch{
z-index:9999;
background:#0071b4;
max-height:260px;
overflow:auto;
width:92%;
box-shadow:0px 2px 4px #444;
margin-left:1.2%;
}
/***********************************/
.live-outer{
width:100%;
height:60px;
border-bottom:1px solid #ccc;
background:#fff;
}
.live-outer:hover{
background:#F3F3F3;
}
.live-im{
float:left;
width:10%;
height:60px;
}
.live-im img{
width:100%;
height:100%;
}
.live-product-det{
float:left;
width:90%;
height:60px;
}
.live-product-name{
width:100%;
height:22px;
margin-top:4px;
}
.live-product-name p{
margin:0px;
color:#333;
text-shadow: 1px 1px 1px #DDDDDD;
font-size:17px;
}
.live-product-price{
width:100%;
height:25px;
}
.live-product-price-text{
float:left;
width:50%;
}
.live-product-price-text p{
margin:0px;
font-size:16px;
}
.link-p-colr{
color:#333;
}
</style>

