<?php require('Template/header.html') ?>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <br>
    <table class="table table-hover">
       <thead>
        <tr><th>Auction Id</th><th>Start </th><th> Item ID</th><th>Posting User</th><th>Item</th><th>Description</th><th>Photo</th></tr>

       
       </thead>   
    <tbody> 
        <?php foreach ($view->itemDataSet as $itemData) {
              echo '<tr> <td>' . $itemData->getAuctionID() . '</td> <td>' . $itemData->getAuctionStart() . '</td> <td>' . $itemData->getItemID() . '</td> <td>' . $itemData->getPostingUser() .'</td> <td>' . $itemData->getItemTitle() . '</td>  <td>' . $itemData->getDescription() . '</td> <td>' . $itemData->getProductImage() . '</td>  </td></tr>';
        } ?>
    </tbody>
  </table>  
</form>

<?php require('Template/footer.html') ?>
