<div class="row">

    <div class="col-8">
        <h1>Catalogue</h1>
    </div>
</div>






<div class="row">
    <div class="col-5">
        <p>Results</p>
    </div>
</div>



<style type="text/css">
    table{
        border-collapse: collapse;
        width: 100%;
        color: #0f0f0f;
        font-family: monospace;
        font-size: 15px;
        text-align: left;
    }
</style>







<?php
$conn = mysqli_connect('poseidon.salford.ac.uk', 'aee318', '1bd6nS33Gt2nDNS','aee318_auction' );
if ($conn-> connect_error) {
    die("connection failed:".$conn-> conenct_error);
}
?>

<?php
$sql = "SELECT * FROM auction limit 10 ";
$resultset = mysqli_query($conn, $sql) or die("database error:". mysqli_error($conn));
while( $record = mysqli_fetch_assoc($resultset) ) {
    ?>
    <div class="card hovercard">
        <div class="cardheader">
            <div class="avatar">
                <img alt="" src="<?php echo $record['productImage']; ?>">
            </div>
        </div>
        <div class="card-body info">
            <div class="title">
                <a href="#">Item Name:<?php echo $record['itemTitle']; ?></a>
            </div>
            <div class="desc"> <a target="_blank" href="<?php echo $record['auctionID']; ?>"></a></div>
            <div class="desc">Description: <?php echo $record['description']; ?></div>
            <div class="desc">Posing User:<?php echo $record['postingUser']; ?></div>
            <div class="desc">Item ID:<?php echo $record['itemID']; ?></div>
            <div class="desc">Auction Start:<?php echo $record['auctionStart']; ?></div>

        </div>
        <div class="card-footer bottom">
            <a class="btn btn-primary  btn-sm" href="card.php">
                <i class="List"> View Product</i>
            </a>
        </div>
    </div>
<?php } ?>












<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item disabled">
            <a class="page-link" href="auction.php?page=0" tabindex="1">&laquo; Previous</a>
        </li>
        <li class="page-item active">
            <a class="page-link" href="auction.php?page=1" tabindex="1">1</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="auction.php?page=2" tabindex="1">2</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="auction.php?page=3" tabindex="1">3</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="auction.php?page=4" tabindex="1">4</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="auction.php?page=5" tabindex="1">5</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="auction.php?page=6" tabindex="1">6</a>
        </li>
        <li class="page-item">
            <a class="page-link" tabindex="1">...</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="auction.php?page=50" tabindex="1">50</a>
        </li>
        <li class="page-item 1">
            <a class="page-link" href="auction.php?page=2" tabindex="2">Next &raquo;</a>
        </li>
    </ul>
</nav>

</div>




<!-- Bootstrap core JavaScript
================================================== -->

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>


<script src="js/bootstrap.min.js"></script>

<script>
    $('#loginErrorModal').modal('show')
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>

</html>