<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="../css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <!-- Bootstrap core CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Bootstrap core CSS -->
    <link href="../css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="../css/bootstrap.theme.css" rel="stylesheet">
    <link href="../css/style.css" rel="stylesheet">
    <title>Search</title>

    <?php

    $view = new stdClass();
    $view->pageTitle = 'Auction';

    require_once ('Template/header.phtml');
    ?>
</head>


<body>

<div class="container">
<br />
<h2 align="center">Search</h2><br />
<div class="form-group">
    <div class="input-group">
        <span class="input-group-addon">Search</span>
        <input type="text" name="search_text" id="search_text" placeholder="Search by Customer Details" class="form-control" />
    </div>
</div>
<br />
<div id="result"></div>
</div>


<script>
    $(document).ready(function(){

        load_data();

        function load_data(query)
        {
            $.ajax({
                url:"view/search.php",
                method:"POST",
                data:{query:query},
                success:function(data)
                {
                    $('#result').html(data);
                }
            });
        }
        $('#search_text').keyup(function(){
            var search = $(this).val();
            if(search != '')
            {
                load_data(search);
            }
            else
            {
                load_data();
            }
        });
    });
</script>
</body>
</html>


<!-- Link to footer-->
<?php

$view = new stdClass();
$view->pageTitle = 'Auction';

require_once ('Template/footer.html');
?>
</html>

<!-- CSS For search bar-->


<style>


    @charset "utf-8";
    /* CSS Document */
    body{
        font-family: 'Rubik', sans-serif;
        background:#BBBBBB;
    }
    /***********************************/
    #lowrbdy{
        width:100%;
        height:581px;
        position:absolute;
        top:74px;
        left:0px;
    }
    #lowrbdy img{
        width:100%;
        height:100%;
    }
    /***********************************/
    header{
        width:100%;
        height:auto;
        background:#adb5bd;
        box-shadow:0px 0px 8px 2px #333;
        position:fixed;
        z-index:99999;
        top:0px;
        left:0px;
    }
    /***********************************/
    .logo{
        width:181px;
        height:61px;
        position:relative;
        top:5px;
        left:10px;
        float:left;
    }
    .logo a{
        text-decoration:none;
        color:#fff;
        font-size:60px;
        margin:0px 20px;
        line-height:0.9em;
    }
    /***********************************/
    .srbox{
        width:580px;
        height:70px;
        float:left;
        margin-left:120px;
        margin-top:4px;
    }
    .textbox{
        border-radius: 8px 0px 0px 8px;
        background-color:#fff;
        float:left;
        border:none;
        height:40px;
        padding:1px 12px;
        font-size:15px;
        line-height: 1.42857;
        color:#000;
        width:420px;
        margin-top:13px;
    }
    .query-submit{
        border-radius: 0px 8px 8px 0px;
        cursor:pointer;
        background:#fbfbfb;
        width:85px;
        padding:1px 6px;
        float:left;
        border:none;
        margin-top:13px;
        height:42px;
    }
    .textbox-clr{
        cursor:pointer;
        background:#fff;
        width:20px;
        height:42px;
        float:left;
        border:none;
        margin-top:13px;
        text-align:center;
    }
    /***********************************/
    .acount{
        width:170px;
        height:30px;
        float:left;
        margin-top:27px;
        margin-left:40px;
    }
    .aclogo{
        width:20px;
        height:20px;
        float:left;
        border:2px solid #fff;
        border-radius:50%;
        text-align:center;
    }
    .actext{
        width:130px;
        float:left;
        line-height:1.6em;
        margin-left:8px;
        font-size:15px;
        color:#fff;
    }
    /***********************************/
    .cart{
        width:120px;
        height:36px;
        float:left;
        border:2px solid #fff;
        border-radius:40px;
        margin-top:18px;
        margin-left:40px;
    }
    .cart i{
        line-height:1.6em;
        color:#fff;
        font-size:20px;
        margin-left:10px;
        float:left;
    }
    .cart-e{
        color:#fff;
        font-size:20px;
        line-height:1.6em;
        float:left;
        margin:0px;
        margin-left:10px;
    }
    .cart-f{
        color:#000;
        float:left;
        background:#fff;
        padding:2px 6px;
        border-radius:50%;
        margin:5px 0px 0px 11px;
        font-size:16px;
        line-height: normal;
    }
    /***********************************/
    #search-layer{
        position:absolute;
        background:rgba(255,255,255,0.5);
        z-index:9;
        left:0px;
        top:0px;
    }
    /***********************************/
    #livesearch{
        z-index:9999;
        background:#0071b4;
        max-height:260px;
        overflow:auto;
        width:92%;
        box-shadow:0px 2px 4px #444;
        margin-left:1.2%;
    }
    /***********************************/
    .live-outer{
        width:100%;
        height:60px;
        border-bottom:1px solid #ccc;
        background:#fff;
    }
    .live-outer:hover{
        background:#F3F3F3;
    }
    .live-im{
        float:left;
        width:10%;
        height:60px;
    }
    .live-im img{
        width:100%;
        height:100%;
    }
    .live-product-det{
        float:left;
        width:90%;
        height:60px;
    }
    .live-product-name{
        width:100%;
        height:22px;
        margin-top:4px;
    }
    .live-product-name p{
        margin:0px;
        color:#333;
        text-shadow: 1px 1px 1px #DDDDDD;
        font-size:17px;
    }
    .live-product-price{
        width:100%;
        height:25px;
    }
    .live-product-price-text{
        float:left;
        width:50%;
    }
    .live-product-price-text p{
        margin:0px;
        font-size:16px;
    }
    .link-p-colr{
        color:#333;
    }
</style>