<!doctype html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>Live Search</title>
    <?php
    include('Search/config.php');
    ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed|Rubik" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <!-- Bootstrap core CSS -->
    <link href="../css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="../css/bootstrap.theme.css" rel="stylesheet">
    <link href="../css/style.css" rel="stylesheet">

</head>

<body>
<!-- Header Link-->

<header>

    <?php

    require_once ('Template2/header2.phtml');
    ?>
</header>

<div id="search-layer"></div>

<div class="row">

    <div class="col-8">
        <h1>Catalogue</h1>
    </div>
</div>






<div class="row">
    <div class="col-5">
        <p>Results</p>
    </div>
</div>



<style type="text/css">
    table{
        border-collapse: collapse;
        width: 100%;
        color: #0f0f0f;
        font-family: monospace;
        font-size: 15px;
        text-align: left;
    }
</style>






<!-- Auction Data-->

<?php
$conn = mysqli_connect('poseidon.salford.ac.uk', 'aee318', '1bd6nS33Gt2nDNS','aee318_auction' );
if ($conn-> connect_error) {
    die("connection failed:".$conn-> conenct_error);
}
?>

<?php
$sql = "SELECT * FROM auction limit 10 ";
$resultset = mysqli_query($conn, $sql) or die("database error:". mysqli_error($conn));
while( $record = mysqli_fetch_assoc($resultset) ) {
    ?>
    <div class="card hovercard">
        <div class="cardheader">
            <div class="avatar">
                <img alt="" src="<?php echo $record['productImage']; ?>">
            </div>
        </div>
        <div class="card-body info">
            <div class="title">
                <a href="#">Item Name:<?php echo $record['itemTitle']; ?></a>
            </div>
            <div class="desc"> <a target="_blank" href="<?php echo $record['auctionID']; ?>"></a></div>
            <div class="desc">Description: <?php echo $record['description']; ?></div>
            <div class="desc">Posing User:<?php echo $record['postingUser']; ?></div>
            <div class="desc">Item ID:<?php echo $record['itemID']; ?></div>
            <div class="desc">Auction Start:<?php echo $record['auctionStart']; ?></div>

        </div>
        <div class="card-footer bottom">
            <a class="btn btn-primary  btn-sm" href="card2.php">
                <i class="List"> View Product</i>
            </a>
        </div>
    </div>
<?php } ?>
<!-- Nav bar for bottom of the page -->

<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item disabled">
            <a class="page-link" href="auction.php?page=0" tabindex="1">&laquo; Previous</a>
        </li>
        <li class="page-item active">
            <a class="page-link" href="auction.php?page=1" tabindex="1">1</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="auction.php?page=2" tabindex="1">2</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="auction.php?page=3" tabindex="1">3</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="auction.php?page=4" tabindex="1">4</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="auction.php?page=5" tabindex="1">5</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="auction.php?page=6" tabindex="1">6</a>
        </li>
        <li class="page-item">
            <a class="page-link" tabindex="1">...</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="auction.php?page=50" tabindex="1">50</a>
        </li>
        <li class="page-item 1">
            <a class="page-link" href="auction.php?page=2" tabindex="2">Next &raquo;</a>
        </li>
    </ul>
</nav>




<?php

$view = new stdClass();
$view->pageTitle = 'Auction';

require_once ('Template2/footer2.html');
?>

<!-- Bootstrap core JavaScript
================================================== -->

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>


<script src="js/bootstrap.min.js"></script>

<script>
    $('#loginErrorModal').modal('show')
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>


</html>





<!-- Style Sheet for search bar-->

<style>


    @charset "utf-8";
    /* CSS Document */
    body{
        font-family: 'Rubik', sans-serif;
        background:#BBBBBB;
    }
    /***********************************/
    #lowrbdy{
        width:100%;
        height:581px;
        position:absolute;
        top:74px;
        left:0px;
    }
    #lowrbdy img{
        width:100%;
        height:100%;
    }
    /***********************************/
    header{
        width:100%;
        height:auto;
        background:#adb5bd;
        box-shadow:0px 0px 8px 2px #333;
        position:fixed;
        z-index:99999;
        top:0px;
        left:0px;
    }
    /***********************************/
    .logo{
        width:181px;
        height:61px;
        position:relative;
        top:5px;
        left:10px;
        float:left;
    }
    .logo a{
        text-decoration:none;
        color:#fff;
        font-size:60px;
        margin:0px 20px;
        line-height:0.9em;
    }
    /***********************************/
    .srbox{
        width:580px;
        height:70px;
        float:left;
        margin-left:120px;
        margin-top:4px;
    }
    .textbox{
        border-radius: 8px 0px 0px 8px;
        background-color:#fff;
        float:left;
        border:none;
        height:40px;
        padding:1px 12px;
        font-size:15px;
        line-height: 1.42857;
        color:#000;
        width:420px;
        margin-top:13px;
    }
    .query-submit{
        border-radius: 0px 8px 8px 0px;
        cursor:pointer;
        background:#fbfbfb;
        width:85px;
        padding:1px 6px;
        float:left;
        border:none;
        margin-top:13px;
        height:42px;
    }
    .textbox-clr{
        cursor:pointer;
        background:#fff;
        width:20px;
        height:42px;
        float:left;
        border:none;
        margin-top:13px;
        text-align:center;
    }
    /***********************************/
    .acount{
        width:170px;
        height:30px;
        float:left;
        margin-top:27px;
        margin-left:40px;
    }
    .aclogo{
        width:20px;
        height:20px;
        float:left;
        border:2px solid #fff;
        border-radius:50%;
        text-align:center;
    }
    .actext{
        width:130px;
        float:left;
        line-height:1.6em;
        margin-left:8px;
        font-size:15px;
        color:#fff;
    }
    /***********************************/
    .cart{
        width:120px;
        height:36px;
        float:left;
        border:2px solid #fff;
        border-radius:40px;
        margin-top:18px;
        margin-left:40px;
    }
    .cart i{
        line-height:1.6em;
        color:#fff;
        font-size:20px;
        margin-left:10px;
        float:left;
    }
    .cart-e{
        color:#fff;
        font-size:20px;
        line-height:1.6em;
        float:left;
        margin:0px;
        margin-left:10px;
    }
    .cart-f{
        color:#000;
        float:left;
        background:#fff;
        padding:2px 6px;
        border-radius:50%;
        margin:5px 0px 0px 11px;
        font-size:16px;
        line-height: normal;
    }
    /***********************************/
    #search-layer{
        position:absolute;
        background:rgba(255,255,255,0.5);
        z-index:9;
        left:0px;
        top:0px;
    }
    /***********************************/
    #livesearch{
        z-index:9999;
        background:#0071b4;
        max-height:260px;
        overflow:auto;
        width:92%;
        box-shadow:0px 2px 4px #444;
        margin-left:1.2%;
    }
    /***********************************/
    .live-outer{
        width:100%;
        height:60px;
        border-bottom:1px solid #ccc;
        background:#fff;
    }
    .live-outer:hover{
        background:#F3F3F3;
    }
    .live-im{
        float:left;
        width:10%;
        height:60px;
    }
    .live-im img{
        width:100%;
        height:100%;
    }
    .live-product-det{
        float:left;
        width:90%;
        height:60px;
    }
    .live-product-name{
        width:100%;
        height:22px;
        margin-top:4px;
    }
    .live-product-name p{
        margin:0px;
        color:#333;
        text-shadow: 1px 1px 1px #DDDDDD;
        font-size:17px;
    }
    .live-product-price{
        width:100%;
        height:25px;
    }
    .live-product-price-text{
        float:left;
        width:50%;
    }
    .live-product-price-text p{
        margin:0px;
        font-size:16px;
    }
    .link-p-colr{
        color:#333;
    }
</style>